server:
    port: 8000
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/kunal1110/config-server-properties.git
